services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS}
    networks:
      - local_dev

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASS}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - local_dev

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    depends_on:
      - mongodb
    networks:
      - local_dev

  backend:
    build:
      context: src/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - local_dev

networks:
  local_dev:
