from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    MONGO_ADMIN_USER: str
    MONGO_ADMIN_PASS: str
    MONGODB_HOST: str
    MONGODB_PORT: int
    MONGODB_DATABASE_NAME: str
    VECTORDB_HOST: str
    VECTORDB_PORT: int
    VECTORDB_PROVIDER: str
    VECTORDB_DISTANCE: str
    ASSET_UNSTRUCTURED_ALLOWED_TYPES: list[str]
    ASSET_UNSTRUCTURED_ALLOWED_SIZE: int
    ASSET_UNSTRUCTURED_UPLOAD_CHUNK_SIZE: int
    GENERATION_LLM_BASE_URL: str
    GENERATION_LLM_MODEL_NAME: str
    GENERATION_LLM_SPECIAL_TOKENS: list[str]
    GENERATION_LLM_MAX_PROMPT_TOKENS: int
    GENERATION_LLM_MAX_OUTPUT_TOKENS: int
    GENERATION_LLM_TEMPERATURE: float
    EMBEDDING_LLM_BASE_URL: str
    EMBEDDING_LLM_MODEL_NAME: str
    EMBEDDING_LLM_SPECIAL_TOKENS: list[str]
    EMBEDDING_LLM_EMBEDDING_SIZE: int
    EMBEDDING_LLM_MAX_PROMPT_TOKENS: int
    OPENAI_API_KEY: str
    WIKIPEDIA_USER_AGENT: str
    WIKIPEDIA_LANGUAGE: str
    USER_AGENT: str
    WANDB_API_KEY: str
    WANDB_PROJECT_NAME: str
    WEAVE_PROJECT_NAME: str
    # GENERATION LLM FOR EVALUATION
    EVAL_LLM_BASE_URL: str
    EVAL_LLM_MODEL_NAME: str
    EVAL_LLM_SPECIAL_TOKENS: list[str]
    EVAL_LLM_MAX_PROMPT_TOKENS: int
    EVAL_LLM_MAX_OUTPUT_TOKENS: int
    EVAL_LLM_TEMPERATURE: float
    EVAL_DATA_NAME: str
    EVAL_DATA_PATH: str

    class Config:
        env_file = ".env"


def get_settings() -> Settings:
    return Settings()
